### ISSUE TITLE
File "env_file: credentials-smtp.env" is missing

### ISSUE THREAD

**Issue by pacoorozco** [juanluisbaptiste/docker-mconf-web#1]
Hiya,

When I try to make a `docker-compose up` it fails with an error. This file `env_file: credentials-smtp.env` is missing.

Can you put some template?

Thanks!

**Comment by juanluisbaptiste** [comment]
Is not missing, you have to create it and put your SMTP creadentials on it. Please see the documentation of the [postfix container](https://github.com/juanluisbaptiste/docker-postfix). I'm missing a README that I will upload in the following days.
