### ISSUE TITLE
bbb fails to start because ulimit is denied  

### ISSUE THREAD

**Issue by chesty** [juanluisbaptiste/docker-mconf-web#2]
Probably not a bug, probably related to my system, but I needed to add
```
  cap_add:
   - SYS_NICE

```
to docker-compose.yaml bbb:

but I still can't get it working, 

"GET /bigbluebutton/rooms/root/join HTTP/1.1" 500 4179

/bigbluebutton/rooms lists the room

I can't see any errors in the bbb container, but I don't really know where to look.
are you able to help?

**Comment by juanluisbaptiste** [comment]
Try with:
  cap_add:
    - ALL

**Comment by chesty** [comment]
thanks for the reply, and thanks for sharing your docker container too.

I'm running it like that now, same problem. I think it might still be freeswitch related.

bbb-fsesl-akka isn't running, and if I start it I get

````
Starting FreeSWITCH ESL connection manager.
[INFO] [04/20/2017 02:32:05.864] [bigbluebutton-fsesl-system-akka.rediscala-subscriber-worker-dispatcher-9] [akka://bigbluebutton-fsesl-system/user/redis-subscriber] Connect to /127.0.0.1:6379
[INFO] [04/20/2017 02:32:05.868] [bigbluebutton-fsesl-system-akka.rediscala-subscriber-worker-dispatcher-9] [akka://bigbluebutton-fsesl-system/user/redis-subscriber] Connected to /127.0.0.1:6379
Unknown message name=[bbb_apps_is_alive_message]
Attempting to connect to FreeSWITCH ESL
Unknown message name=[bbb_apps_is_alive_message]
Subscribing for ESL events.
Unknown message name=[bbb_apps_is_alive_message]
ESL Event Listener received event=[HEARTBEAT]
Unknown message name=[bbb_apps_is_alive_message]
```

**Comment by juanluisbaptiste** [comment]
Please test tag 0.8.1-5bd1fac1, latest may be pointing to dev build of my work on 1.x.

**Comment by chesty** [comment]
legendary, that was it. It's working now.
